@baseUrl = http://localhost:8000
@token = 2|em0QEsRzPrQR7ypPMbJesBkwqw5b4SfJ27Yd0C1W34d0f15b

### Register
POST {{baseUrl}}/api/register
Content-Type: application/json
Accept: application/json

{
    "name": "Test User",
    "email": "test@example.com",
    "password": "password"
}

### Login
POST {{baseUrl}}/api/login
Content-Type: application/json
Accept: application/json

{
    "email": "test@example.com",
    "password": "password"
}

### Logout
POST {{baseUrl}}/api/logout
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

### View Posts
GET {{baseUrl}}/api/posts
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

### View Post
GET {{baseUrl}}/api/posts/1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

### Create Post
POST {{baseUrl}}/api/posts
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
    "title": "Test Post",
    "text": "This is a test post"
}

### Update Post
PUT {{baseUrl}}/api/posts/1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
    "title": "Test Post",
    "text": "This is an updated test post"
}

### Delete Post
DELETE {{baseUrl}}/api/posts/1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

### Make Comment
POST {{baseUrl}}/api/comments
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
    "post_id": 1,
    "text": "This is a test comment"
}

### Reply to Comment
POST {{baseUrl}}/api/comments
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
    "post_id": 1,
    "comment_id": 1,
    "text": "This is a test reply"
}

### View Comments
GET {{baseUrl}}/api/comments
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

### View Comment
GET {{baseUrl}}/api/comments/1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

### Update Comment
PUT {{baseUrl}}/api/comments/1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
    "text": "This is an updated test comment"
}

### Delete Comment
DELETE {{baseUrl}}/api/comments/1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}